### ISSUE TITLE
mangafox issue with downloads

### ISSUE THREAD

**Issue by anshbansal** [riderkick/FMD#168] opened 2016-01-23 18:45 UTC
From past few weeks anything downloads from Mangafox stop suddenly. 
- My internet is working
- the website is working (verified via browser) 
- The files are present on the website.
Still from FMD the downloads are stopping for mangafox only

**Comment by riderkick** [comment] 2016-01-24 00:10
Title, chapters?
I don't have any problem.
Is there any error message?

**Comment by greenaar** [comment] 2016-01-24 00:32
They appear to have added a delay for newly opened connections. I have noticed this week the 'check for new chapters' in fmd takes a long time to parse mangafox entries.  Opening one in a browser results in a delay of up to 15 seconds.  While that window is open, viewing subsequent pages appears to be normal speed, but opening a new browser window results in a delay of equal length.

**Comment by riderkick** [comment] 2016-01-24 00:43
Yup I notice that too. 
I don't know what is matter, cookies? Even with existing cookies, when opening new instance(tab) it also have a delay, so I don't think it was the cookies.

**Comment by riderkick** [comment] 2016-01-24 01:49
I don't know what happen, but it seems the issue is gone.
Maybe it's temporary server issue. maybe they do something with their server, maintenance/migration. Can you test it?

**Comment by greenaar** [comment] 2016-01-24 01:57
I can reliably repro the issue.  Choosing to view manga info (on a mangafox manga) times out.  Going from an open mangafox connection in one browser tab, and either opening a link in a new tab, or copying the existing url to a new tab == 15+ second delay.  I don't think it's cookie based, I'd suspect they're doing something with persistent connections, where new connections are greylisted -- but I'm only guessing.  I can further add (just noticed) that an open tab which has been working, but is left alone for a while idle will experience the same symptoms, which is quite like the persistent connection timeout expiring, and the connection being treated as new.

**Comment by riderkick** [comment] 2016-01-24 02:03
I just checked, seems they/we don't use keep-alive connection.
And I just load the website after a few minutes, there is no problem.

**Comment by riderkick** [comment] 2016-01-24 02:06
I just checked, seems they/we don't use keep-alive connection.
And I just load the website after a few minutes, there is no problem.

**Comment by greenaar** [comment] 2016-01-24 02:30
Interesting.  The issue is still ongoing here.  Please note though, I'm not saying this is a FMD issue, it's definitely not, as it repros in a browser.

**Comment by riderkick** [comment] 2016-01-24 02:38
What is your country origin? I'm using vpn from Singapore. It seems there is no issue. But it does have issue with USA and the rest.

**Comment by greenaar** [comment] 2016-01-24 02:42
Canada.  It suddenly got better.  I can only assume it was an actual problem on their end, vs a new method of blocking downloaders.

**Comment by riderkick** [comment] 2016-01-25 11:03
I don't have this issue anymore. I think it really is temporary issue in their server. I'll close this issue.

**Closed by riderkick** 2016-01-25 11:03 UTC
