### ISSUE TITLE
list update improvement request

### ISSUE THREAD

**Issue by formigao** [riderkick/FMD#157] opened 2016-01-11 20:32 UTC
current Batoto is just too slow to update.
and it need to add 1500+ extra entries.

i tried to do it for 3 hours and then the program crashes with only 800 analized.

and i need to start again from the beginning

My ideas for improvements:

1° put some save points for every 100 or 200 entries so we dont lose everything if the program crash

2° show date for when the last update was done and when was the last time the server data was updated.
 so we can compare what is the best option. 

downloading is 100000000X faster than checking one by one. put can backfire if you download a outdated version and you will need to update more than if you just have done if in the first place.

thanks for the attention

**Comment by riderkick** [comment] 2016-01-11 21:37
Crash report/log?

1. Data committed every 32 entries. If program crash you just lost 32 entries at max. https://github.com/riderkick/FMD/blob/master/baseunits/uUpdateThread.pas#L229
2. The best option is always been to update manually. We only getting what doesn't exist in local database. The first always been the longer. For a website who doesn't have sorted list, we have to load all the manga directory every time we update the manga list.

I don't have enough resource to maintain the manga list. That's why the manga list data on server(bintray) barely getting updates.
I'm alone here. Putting it in github hoping for someone to find interest and join the team. Unfortunately there is none. yet.

If you getting hard time with manga list, than don't use it. Just put the url in mangainfo tab to download/add to favorites. Browse their website if you want to search something. Visiting their website will help their cause. They need money to keep their website alive. Personally, I never used manga list since I step in to maintain this project.

**Comment by riderkick** [comment] 2016-01-11 21:57
Batoto indeed very slow. On my computer the server take  ~5s before replying. Whether it's their server limitation or intended. You know they have hard time maintaining their bandwidth, and they do limit the concurrent connection to their server. Currently max connection for batoto in fmd is 2.

**Comment by formigao** [comment] 2016-01-11 21:58
where can i find this crash log ?

i tried to update 3 times and the programs just close after some time. and always have the same number needed to update again.

so its not saving every 32.

yes i know about batoto slow.

i have not a problem with it i cna let te program update one day.

the problem is the crash after 2 hours for nothing.

**Comment by riderkick** [comment] 2016-01-11 22:02
fmd.log

**Comment by formigao** [comment] 2016-01-11 22:04
the file is empty

**Comment by riderkick** [comment] 2016-01-11 22:09
The file will not be created if there is nothing to be written. So it's very unlikely if it's empty.

**Comment by formigao** [comment] 2016-01-11 22:13
i must have cleaned it the last time i solved a problem.
but for now the program is closing but not letting any log.

**Comment by riderkick** [comment] 2016-01-11 22:18
If the program doesn't throw any error then there will be no log. Or it's close normally without any problem.

Batoto has sorted list, so it will not be saved if it's interrupted. It has to be lose, because there will be some title missing that can't be recovered in the next update.
The advantage of sorted list is we don't need to load all the directory list to update it will stop at the first hit in database.

**Comment by formigao** [comment] 2016-01-11 22:29
i did some test here.

i let the program update till 50 of 1568.

them i cancelled the task.

i tried again. and yet i had 1568 entries to update

so the data is not being written every 32 entries.

**Comment by riderkick** [comment] 2016-01-11 22:32
Batoto has sorted list. Like I explain above, it has to be lose.

**Comment by formigao** [comment] 2016-01-11 22:37
hum so no way to update batoto =/

the program never finish the whole 1568 entries needed. it crash after 700+.

**Comment by riderkick** [comment] 2016-01-11 22:45
If it crash, then there is should be a log. If not then it close normally.
You can try to run fmd with parameter "-LOGACTIVE 4". There will be additional log file in "log" folder.

**Comment by formigao** [comment] 2016-01-11 22:50
giving it a try.

 i will post results again if te program crash

**Comment by formigao** [comment] 2016-01-11 23:57
program closed again.


log file only have it.

fmd_LOG_11-01-2016

11/01/2016|20:49:29.364 [I] Starting "Free Manga Downloader"

program just dont give a error it just randomly closes without any warning.

**Comment by riderkick** [comment] 2016-01-12 00:06
If you remember on which page it crash.
If you have firewall log, you should be able to find out the last request from fmd.

**Comment by formigao** [comment] 2016-01-12 00:20
nothing.
it's not always on the same page.
it just happen randomly.
sometimes at 600+ other at 700.
and the last one crashed 260.

**Comment by riderkick** [comment] 2016-01-12 00:42
Weird, it should write something. Except if its killed by other process, like task manager.
If there is error within it should write to log file. And usually there is error dialog.

**Comment by formigao** [comment] 2016-01-12 00:44
yes. one time the program is open then it closes without a warning.
try to update batoto maybe you can reproduce the problem.
maybe even download the server list so it will be outdated a lot and test to see if the program can finish all the 1500+ entries

**Comment by riderkick** [comment] 2016-01-12 00:46
I'm trying to run update list, very slow indeed.
Even if 4 connection running, it seems their server only serve 1 at a time. And there is always ~5s delay.

**Comment by formigao** [comment] 2016-01-12 00:51
let's see if you get the same error.
would be great if others people could try to reproduce the problem too.

maybe it's because is just to much do to at once ?

max i saw the program go is 700-800

**Comment by riderkick** [comment] 2016-01-12 00:54
No, It should be able to go infinite.
Except if there is bug introduced with recent changes. But IIRC I did't touch updatemanager for a long time.

**Comment by riderkick** [comment] 2016-01-12 05:09
Well, I able to finish without problem.
http://i.minus.com/ibwGsvji3q72sa.jpg

Minor changes was applied, but I think it should not matter.
Did you set fmd to automatically close when download finish? Maybe there is download task running, can be added automatically when checking favorites, if auto check favorites activated.

**Comment by formigao** [comment] 2016-01-12 15:46
weird... could it be with just me ?

and no my fmd dont close when end dl.  also i didnt do nothing with the program only asked to update the list.

can you upload the updated file for me ?  with less things to update at once i think i can keep it updated from now on.

**Comment by lazypete365** [comment] 2016-01-12 21:11
I'm not sure if I'm reproducing the same problem, but I'm certainly having trouble updating my lists too. After a while trying to update all lists, FMD throws any of a number of dialog boxes (including an empty exception box), if I click terminate it just freezes and I have to kill it via task manager and the log doesn't always update.

Some examples I got in different runs:

![crash_fmd](https://cloud.githubusercontent.com/assets/9962097/12276906/b6de3076-b978-11e5-8b3d-bd7a9ccf0c44.png)
![crash_fmd_2](https://cloud.githubusercontent.com/assets/9962097/12276910/b93d7836-b978-11e5-9341-cf4450721c7d.png)

Also, the latest addition to the log from a run when it did generate a proper exception:
```
Failed to create exception FLastReport!
Sender Class      : TUpdateMangaManagerThread
Exception Class   : EInvalidPointer
Message           : Invalid pointer operation

Sender Class: TUpdateMangaManagerThread
EInvalidPointer: Invalid pointer operation
Exception Class   : EInvalidPointer
Message           : Invalid pointer operation
Exception Address : $00000001000133F3
  $00000001002AA8C8 line 333 of ../baseunits/SimpleException/USimpleException.pas
  $00000001002A9EE5 line 263 of ../baseunits/SimpleException/USimpleException.pas
  $00000001002AAC80 line 411 of ../baseunits/SimpleException/USimpleException.pas
  $0000000100018AB0 line 421 of seh64.inc
  $00000000775290DD
  $000000007751848C
  $00000000773104FE
  $00000001000188E9 line 396 of seh64.inc
  $000000007752905D
  $0000000077518C0F
  $0000000077519208
  $000007FEFD31B3DD
  $00000001000185FE line 293 of seh64.inc
  $000000010007F08C line 432 of ../objpas/sysutils/sysutils.inc
  $0000000100011FB8 line 1126 of ../inc/system.inc
  $0000000100012052 line 1143 of ../inc/system.inc

Sender Class      : TUpdateMangaManagerThread
Exception Class   : EInvalidPointer
Message           : Invalid pointer operation
Exception Address : $00000001000133F3
  $00000000773104FE
  $0000000100018C64 line 505 of seh64.inc
  $000000007752905D
  $0000000077518C0F
  $0000000077519208
  $000007FEFD31B3DD
  $00000001000185FE line 293 of seh64.inc
  $000000010007F08C line 432 of ../objpas/sysutils/sysutils.inc
  $0000000100011FB8 line 1126 of ../inc/system.inc
  $0000000100012052 line 1143 of ../inc/system.inc
  $0000000100012081 line 1163 of ../inc/system.inc
  $00000001000133F3 line 1152 of ../inc/heap.inc
  $000000010001357D line 1230 of ../inc/heap.inc
  $00000001000135BD line 1241 of ../inc/heap.inc
  $0000000100013055 line 959 of ../inc/heap.inc
  $00000001000132A7 line 1072 of ../inc/heap.inc

Sender Class      : TUpdateMangaManagerThread
Exception Class   : EInvalidPointer
Message           : Invalid pointer operation
Exception Address : $00000001000133F3
  $00000000773104FE
  $0000000100018C64 line 505 of seh64.inc
  $000000007752905D
  $0000000077518C0F
  $0000000077519208
  $000007FEFD31B3DD
  $00000001000185FE line 293 of seh64.inc
  $000000010007F08C line 432 of ../objpas/sysutils/sysutils.inc
  $0000000100011FB8 line 1126 of ../inc/system.inc
  $0000000100012052 line 1143 of ../inc/system.inc
  $0000000100012081 line 1163 of ../inc/system.inc
  $00000001000133F3 line 1152 of ../inc/heap.inc
  $000000010001357D line 1230 of ../inc/heap.inc
  $00000001000135BD line 1241 of ../inc/heap.inc
  $0000000100013055 line 959 of ../inc/heap.inc
  $00000001000132A7 line 1072 of ../inc/heap.inc

Sender Class      : TUpdateMangaManagerThread
Exception Class   : EInvalidPointer
Message           : Invalid pointer operation
Exception Address : $0000000100013723
  $000000010005EAE3 line 318 of ../objpas/classes/collect.inc
  $00000001004E0E17 line 136 of fcl-db/src/base/dsparams.inc
  $00000001004E16B0 line 373 of fcl-db/src/base/dsparams.inc
  $00000001004E1073 line 218 of fcl-db/src/base/dsparams.inc
  $00000001004C74C2 line 905 of fcl-db/src/sqldb/sqldb.pp
  $00000001004CC613 line 2374 of fcl-db/src/sqldb/sqldb.pp
  $00000001000645A0 line 1178 of ../objpas/classes/stringl.inc
  $0000000100064947 line 1308 of ../objpas/classes/stringl.inc
  $0000000100063526 line 797 of ../objpas/classes/stringl.inc
  $0000000100062F05 line 653 of ../objpas/classes/stringl.inc
  $0000000100063007 line 639 of ../objpas/classes/stringl.inc
  $0000000100063046 line 661 of ../objpas/classes/stringl.inc
  $00000001004CB29C line 1955 of fcl-db/src/sqldb/sqldb.pp
  $00000001004CE18D line 2971 of fcl-db/src/sqldb/sqldb.pp
  $00000001004E6D1C line 2425 of fcl-db/src/base/bufdataset.pas
  $00000001004CDE64 line 2872 of fcl-db/src/sqldb/sqldb.pp

Sender Class      : TUpdateMangaManagerThread
Exception Class   : EInvalidPointer
Message           : Invalid pointer operation
Exception Address : $0000000100013723
  $00000001000767F0 line 940 of ../objpas/sysutils/sysstr.inc
  $0000000100457172 line 499 of ../baseunits/uUpdateThread.pas
  $00000001004582F2 line 690 of ../baseunits/uUpdateThread.pas
  $000000010006518D line 198 of ../objpas/classes/classes.inc
  $0000000100003376 line 65 of md.lpr
  $00000001000146D7 line 230 of ../win/systhrd.inc
  $0000000076C95A4D
  $0000000076DCB831

Sender Class      : TUpdateMangaManagerThread
Exception Class   : EInvalidPointer
Message           : Invalid pointer operation
Exception Address : $0000000100013723
  $00000001000767F0 line 940 of ../objpas/sysutils/sysstr.inc
  $0000000100457172 line 499 of ../baseunits/uUpdateThread.pas
  $00000001004582F2 line 690 of ../baseunits/uUpdateThread.pas
  $000000010006518D line 198 of ../objpas/classes/classes.inc
  $0000000100003376 line 65 of md.lpr
  $00000001000146D7 line 230 of ../win/systhrd.inc
  $0000000076C95A4D
  $0000000076DCB831

Sender Class      : TUpdateMangaManagerThread
Exception Class   : EAccessViolation
Message           : Access violation
Exception Address : $0000000100013897
  $00000001000138ED line 1241 of ../inc/heap.inc
  $0000000100013385 line 959 of ../inc/heap.inc
  $00000001000135D7 line 1072 of ../inc/heap.inc
  $0000000100013C22 line 1468 of ../inc/heap.inc
  $00000001000128EB line 342 of ../inc/heap.inc
  $000000010000B4C5 line 787 of ../inc/astrings.inc
  $000000010000A54A line 266 of ../inc/astrings.inc
  $00000001000761D3 line 381 of ../objpas/sysutils/sysformt.inc
  $00000001000767F0 line 940 of ../objpas/sysutils/sysstr.inc
  $0000000100457172 line 499 of ../baseunits/uUpdateThread.pas
  $00000001004582F2 line 690 of ../baseunits/uUpdateThread.pas
  $000000010006518D line 198 of ../objpas/classes/classes.inc
  $0000000100003376 line 65 of md.lpr
  $00000001000146D7 line 230 of ../win/systhrd.inc
  $0000000076C95A4D
  $0000000076DCB831
```

It isn't exactly a new problem, either. For a very long time, trying to update all lists just meant that FMD started, but after updating a few site lists it eventually just froze (not necessarily in the same spot), usually without throwing an exception. I couldn't close the program normally either, just kill it.

**Comment by riderkick** [comment] 2016-01-13 04:05
That's very chaotic error. Did you run multiple instance of fmd in the same folder. Because we use sqlite database, we can't run multiple instance of fmd in the same folder with the same data file.
It seems only occurred when running for a long time, whether due to unstable database library or there is flaw in certain script/module.

**Comment by riderkick** [comment] 2016-01-13 06:15
If you update multiple website add once there is indeed a bug. 
https://github.com/riderkick/FMD/commit/98299e006a640b1ab90548fe5e04f3a5b0acb0e8
And more fix and improvement after that commit.

**Comment by riderkick** [comment] 2016-01-13 11:30
I did reproduce the issue, fmd closed unexpectedly. And no exception message.
```
13/01/2016|14:21:00.046 [I] Starting "Free Manga Downloader" [PID:5820] [HANDLE:4294967295]
13/01/2016|14:21:12.476 [V] TUpdateMangaManagerThread, thread started
13/01/2016|14:21:12.552 [V] TUpdateMangaManagerThread, Authrone: update list started
13/01/2016|14:21:12.552 [V] TUpdateMangaManagerThread, Authrone: sortedlist=True; nomangainfo=False
13/01/2016|14:21:12.552 [V] TUpdateMangaManagerThread, Authrone: prepare database file
13/01/2016|14:21:12.594 [V] TUpdateMangaManagerThread, Authrone: get number of directory page
13/01/2016|14:21:16.198 [V] TUpdateMangaManagerThread, Authrone: get names and links
13/01/2016|14:43:39.463 [V] TUpdateMangaManagerThread, Authrone: get info 9418
13/01/2016|17:49:13.592 [V] FormDestroy, freeing all objects
13/01/2016|17:49:13.599 [I] "Free Manga Downloader" exit normally [PID:5820] [HANDLE:4294967295]
```

Strange thing this is happening for a brief after I interact with fmd after its minimized for hours.
And the heap trace
```
F:\GitRepo\Freepascal\FMD\bin\fmd.exe 
Marked memory at $0C5E6230 invalid
Wrong signature $5A7E8CE1 instead of 5A7E8CE1
  $00418A7E
  $00884C6B
  $008834AE
  $008830BD
  $00871AB3
  $00871B87
  $00873666
  $00803734  TUPDATEMANGAMANAGERTHREAD__GETINFO,  line 512 of F:/GitRepo/Freepascal/FMD/baseunits/uUpdateThread.pas
  $008044A2  TUPDATEMANGAMANAGERTHREAD__EXECUTE,  line 682 of F:/GitRepo/Freepascal/FMD/baseunits/uUpdateThread.pas
  $0046B855
  $0041285E
  $75CF336A
  $771A9882
  $771A9855
Heap dump by heaptrc unit
243437501 memory blocks allocated : 3937424687/4262749712
243411414 memory blocks freed     : 3935816033/4261110232
26087 unfreed memory blocks : 1608654
True heap size : 4390912
True free heap : 1046192
Should be : 1081864
Call trace for block $0C5900C8 size 4
  $0086594F
  $0086C246
  $00869279
  $008691DA
  $007791B5  TDBDATAPROCESS__ADDDATA,  line 883 of F:/GitRepo/Freepascal/FMD/baseunits/uData.pas
  $0077935F  TDBDATAPROCESS__ADDDATA,  line 894 of F:/GitRepo/Freepascal/FMD/baseunits/uData.pas
  $007D93C5  TMANGAINFORMATION__ADDINFOTODATA,  line 3165 of F:/GitRepo/Freepascal/FMD/baseunits/uData.pas
Call trace for block $0C6B0BF0 size 378
  $00871AB3
  $00871B87
  $00873666
  $00802240  TUPDATEMANGATHREAD__EXECUTE,  line 223 of F:/GitRepo/Freepascal/FMD/baseunits/uUpdateThread.pas
  $0046B855
  $0041285E
  $75CF336A
Call trace for block $04A24340 size 16
  $008834AE
  $008830BD
  $00871AB3
  $00871B87
  $00873666
  $00802240  TUPDATEMANGATHREAD__EXECUTE,  line 223 of F:/GitRepo/Freepascal/FMD/baseunits/uUpdateThread.pas
  $0046B855
  $04A243BC
Call trace for block $04A242E0 size 16
  $008834AE
  $008830BD
  $00871AB3
  $00871B87
  $00873666
  $00802240  TUPDATEMANGATHREAD__EXECUTE,  line 223 of F:/GitRepo/Freepascal/FMD/baseunits/uUpdateThread.pas
  $0046B855
Call trace for block $04A24280 size 16
  $008834AE
  $008830BD
  $00871AB3
  $00871B87
  $00873666
  $00802240  TUPDATEMANGATHREAD__EXECUTE,  line 223 of F:/GitRepo/Freepascal/FMD/baseunits/uUpdateThread.pas
  $0046B855
  $F0F0F0F0
Call trace for block $04A24220 size 16
  $008834AE
  $008830BD
  $00871AB3
  $00871B87
  $00873666
  $00802240  TUPDATEMANGATHREAD__EXECUTE,  line 223 of F:/GitRepo/Freepascal/FMD/baseunits/uUpdateThread.pas
  $0046B855
  $04A2429C
Call trace for block $04A241C0 size 16
  $008834AE
  $008830BD
  $00871AB3
  $00871B87
  $00873666
  $00802240  TUPDATEMANGATHREAD__EXECUTE,  line 223 of F:/GitRepo/Freepascal/FMD/baseunits/uUpdateThread.pas
  $0046B855
Call trace for block $04A24160 size 23
  $0086DF6E
  $008834D7
  $008830BD
  $00871AB3
  $00871B87
  $00873666
  $00802240  TUPDATEMANGATHREAD__EXECUTE,  line 223 of F:/GitRepo/Freepascal/FMD/baseunits/uUpdateThread.pas
  $F0F0F0F0
Call trace for block $04A24100 size 16
  $008834AE
  $008830BD
  $00871AB3
  $00871B87
  $00873666
  $00802240  TUPDATEMANGATHREAD__EXECUTE,  line 223 of F:/GitRepo/Freepascal/FMD/baseunits/uUpdateThread.pas
  $0046B855
  $04A2417C
Call trace for block $0C6B0A20 size 378
  $00871AB3
  $00871B87
  $00873666
  $00802240  TUPDATEMANGATHREAD__EXECUTE,  line 223 of F:/GitRepo/Freepascal/FMD/baseunits/uUpdateThread.pas
  $0046B855
  $0041285E
  $75CF336A
Call trace for block $04A240A0 size 16
  $008834AE
  $008830BD
  $00871AB3
  $00871B87
  $00873666
  $00802240  TUPDATEMANGATHREAD__EXECUTE,  line 223 of F:/GitRepo/Freepascal/FMD/baseunits/uUpdateThread.pas
  $0046B855
Call trace for block $04A24040 size 16
  $008834AE
  $008830BD
  $008
```

I suspect the culprit is unstable database library. Because those line secured with try..except clause, so if there is any error, it should throw exception.

**Comment by formigao** [comment] 2016-01-13 15:55
good work riderkick !!!

hope you can fix this bug.

**Comment by riderkick** [comment] 2016-01-14 05:17
Well, I'm trying to use latest sqlite dll from https://www.sqlite.org/download.html
And update list have been running  for 6 hours without any problem. You can give it a try. Reminder, latest version of fmd has a bug when updating multiple list, so just update 1 list like batoto, which is require long time due to its slowness.

**Comment by riderkick** [comment] 2016-01-15 13:56
I think I found the real culprit. I still don't understand how it can throw access violation. And why it crash the entire process.
```
15/01/2016|21:27:37.805 [I] Starting "Free Manga Downloader" [PID:4152] [HANDLE:4294967295]
15/01/2016|21:27:40.589 [D] TUpdateMangaManagerThread, thread started
15/01/2016|21:27:40.590 [D] TUpdateMangaManagerThread, MangaTraders: update list started
15/01/2016|21:27:40.591 [D] TUpdateMangaManagerThread, MangaTraders: sortedlist=False; nomangainfo=False
15/01/2016|21:27:40.591 [D] TUpdateMangaManagerThread, MangaTraders: prepare database file
15/01/2016|21:27:40.653 [D] TUpdateMangaManagerThread, MangaTraders: get number of directory page
15/01/2016|21:27:41.061 [D] TUpdateMangaManagerThread, MangaTraders: get names and links
15/01/2016|21:28:11.266 [D] TUpdateMangaManagerThread, MangaTraders: get info 9705
15/01/2016|21:28:13.213 [E] TDBDataProcess[__MangaTraders_templist].GetValue.Error! RecIndex: 821, FieldIndex: 0, RecordCount: 850
Sender Class      : TDBDataProcess
Exception Class   : EAccessViolation
Exception Message : Access violation
Exception Address : $0040373F
  $00817E59
  $0082CE27
  $0082CA0D
  $0081B473
  $0081B547
  $0081CFC6
  $007ACB0C TUPDATEMANGAMANAGERTHREAD__GETINFO, line 519 of F:/GitRepo/Freepascal/FMD/baseunits/uUpdateThread.pas
  $007AD902 TUPDATEMANGAMANAGERTHREAD__EXECUTE, line 697 of F:/GitRepo/Freepascal/FMD/baseunits/uUpdateThread.pas
  $004680B5
  $0041278E
  $75AD336A
  $77339882
  $77339855
15/01/2016|21:28:17.347 [D] TMainForm.FormDestroy, freeing all objects
```

**Closed** 2016-01-15 14:42 UTC
Labels: bug-confirmed
