### ISSUE TITLE
"Incomplete" download marked as completed and different filename downloaded

### ISSUE THREAD

**Issue by rbwz** [riderkick/FMD#331] opened 2016-07-22 18:06 UTC
While downloading using FMD : http://exhentai.org/g/840722/a76cd4c8e1/
Some pages was not downloaded but the task is marked as completed, I tried re-download with no success. When i re-download to other path, different files were successfully downloaded while others failed to download.

I also noticed that unlike other tasks, where the image filename is identical between online reading and downloaded ones, this particular task seems to add a "0" (zero) in front, and truncated several characters of the filename ending on its downloaded filenames.

maybe worth looking into

**Comment by rbwz** [comment] 2016-07-22 18:16
![fela hame](https://cloud.githubusercontent.com/assets/19768117/17066778/ce178472-5072-11e6-823c-36880530f89d.JPG)
file property on the left downloaded using FMD, on the right by right click>save image from browser

**Comment by riderkick** [comment] 2016-07-22 21:42
Read #217 
It seems your download path is too long, and the remain character left for filename is 8, so it's truncated.
Windows max path length is 260.

**Comment by rbwz** [comment] 2016-07-22 22:49
I have just counted, and the total filename+path is not even exceeding 100 characters.

I also noted that not all files has its name truncated, all of it got extra "zero" in front, but only some got axed on the last one or two character.
![fmd03](https://cloud.githubusercontent.com/assets/19768117/17073211/e1b3a5d0-5098-11e6-9b59-d43b3854c2e3.JPG)
the selected files on the pictures got the complete filename, albeit with extra "zero" in front, while the rest got truncated a character or two...

**Comment by riderkick** [comment] 2016-07-27 03:36
I need your works.ini and config.in
I need to see your "Save to" options and custom filename in download task

**Comment by rbwz** [comment] 2016-07-28 18:05
**works.ini:**
[general]
NumberOfTasks=1

[task0]
Website=ExHentai
Link=http://exhentai.org/g/840722/a76cd4c8e1/
Title=[Fue] Fella Hame Lips [English]
SaveTo=E:\fmd\160722\[Fue] Fella Hame Lips [English]\
Status=Completed
Progress=
Enabled=1
DateTime=42574.0120460764
CustomFileName=%FILENAME%
ChapterLinks=/g/840722/a76cd4c8e1/!%~
ChapterName=0001!%~
Filenames=000_!%~000_!%~000_!%~000_!%~000_!%~000_!%~001_!%~001_!%~001_!%~001_!%~002_!%~002_!%~002_!%~002_!%~002_!%~002_!%~002_!%~002_!%~002_!%~002_10!%~002_11!%~002_12!%~002_13!%~002_14!%~002_15!%~002_16!%~002_17!%~002_18!%~002_19!%~002_20!%~002_21!%~002_22!%~002_23!%~002_24!%~003_!%~003_!%~003_!%~003_!%~003_!%~003_!%~003_!%~003_!%~003_!%~003_10!%~003_11!%~003_12!%~003_13!%~003_14!%~003_15!%~003_16!%~003_17!%~003_18!%~003_19!%~003_20!%~003_21!%~003_22!%~003_23!%~003_24!%~003_25!%~003_26!%~003_27!%~003_28!%~004_!%~004_!%~004_!%~004_!%~004_!%~004_!%~004_!%~004_!%~004_!%~004_10!%~004_11!%~004_12!%~004_13!%~004_14!%~004_15!%~004_16!%~004_17!%~004_18!%~004_19!%~004_20!%~004_21!%~004_22!%~004_23!%~004_24!%~004_25!%~004_26!%~004_27!%~004_28!%~004_29!%~004_30!%~004_31!%~004_32!%~005_!%~005_!%~005_!%~005_!%~005_!%~005_!%~005_!%~005_!%~005_!%~005_10!%~005_11!%~005_12!%~005_13!%~005_14!%~005_15!%~005_16!%~005_17!%~005_18!%~005_19!%~005_20!%~005_21!%~005_22!%~005_23!%~005_24!%~005_25!%~005_26!%~005_27!%~005_28!%~005_29!%~005_30!%~006_!%~006_!%~006_!%~006_!%~006_!%~006_!%~006_!%~006_!%~006_!%~006_10!%~006_11!%~006_12!%~006_13!%~006_14!%~006_15!%~006_16!%~006_17!%~006_18!%~006_19!%~006_20!%~006_21!%~006_22!%~006_23!%~006_24!%~006_25!%~006_26!%~006_27!%~006_28!%~006_29!%~006_30!%~006_31!%~006_32!%~006_33!%~006_34!%~006_35!%~006_36!%~007_!%~007_!%~007_!%~007_!%~007_!%~007_!%~007_!%~007_!%~007_!%~007_10!%~007_11!%~007_12!%~007_13!%~007_14!%~007_15!%~007_16!%~008_!%~008_!%~008_!%~008_!%~008_!%~008_!%~008_!%~008_!%~008_!%~008_10!%~008_11!%~008_12!%~008_13!%~008_14!%~008_15!%~008_16!%~008_17!%~008_18!%~008_19!%~008_20!%~008_21!%~008_22!%~008_23!%~008_24!%~008_25!%~008_26!%~008_27!%~008_28!%~008_29!%~008_30!%~008_31!%~008_32!%~008_33!%~008_34!%~009_!%~009_!%~009_!%~009_!%~009_!%~009_!%~010_!%~010_!%~010_!%~010_!%~010_!%~010_!%~
TaskStatus=STATUS_FINISH
ChapterPtr=0
NumberOfPages=222
CurrentPage=0



**config.ini:**
[general]
DownloadFilterSelect=1
MangaListSelect=AnimeA,MangaFox,MangaHere,MangaInn,MangaReader
LiveSearch=1
OneInstanceOnly=1
MinimizeToTray=0
LetFMDDo=0
ExternalProgramPath=
ExternalProgramParams="%PATH%%CHAPTER%"
ChapterListHideDownloaded=0
AddAsStopped=1
HighlightNewManga=1
HighlightDownloadedChapters=1

[languages]
Selected=en

[view]
ShowDownloadsToolbar=1
LoadMangaCover=0

[droptarget]
Show=0
Mode=0
Opacity=255
Width=64
Heigth=64
Top=-1
Left=-1

[connections]
NumberOfTasks=1
NumberOfThreadsPerTask=6
Retry=-1
ConnectionTimeout=30
UseProxy=0
ProxyType=SOCKS5
Host=123.56.199.203
Pass=
Port=1080
User=

[saveto]
SaveTo=E:\fmd\
ChangeUnicodeCharacter=0
GenerateMangaFolder=1
MangaCustomRename=%MANGA%
Compress=0
PDFQuality=100
RemoveMangaNameFromChapter=1
GenerateChapterFolder=1
ChapterCustomRename=%NUMBERING%
ConvertDigitVolume=1
ConvertDigitChapter=1
DigitVolumeLength=2
DigitChapterLength=3
FilenameCustomRename=%FILENAME%

[update]
AutoCheckLatestVersion=0
AutoCheckFavStartup=1
AutoCheckFavInterval=1
AutoCheckFavIntervalMinutes=60
NewMangaTime=1
AutoCheckFavAutoDownload=0
AutoCheckFavAutoRemoveCompletedManga=0
UpdateListNoMangaInfo=0
UpdateListRemoveDuplicateLocalData=0

[dialogs]
ShowQuitDialog=1
ShowDeleteDldTaskDialog=1
ShowDownloadMangalistDialog=1

[Batoto]
ShowAllLang=0
ShowScanGroup=0

[MangaFox]
RemoveWatermark=1
SaveAsPNG=0

[E-Hentai]
DownloadOriginalImage=0
SettingsImageSize=1

[form]
MainSplitter=195
pcMainPageIndex=1
SelectManga=0
MainFormMaximized=1
MainFormLeft=708
MainFormTop=10
MainFormWidth=640
MainFormHeight=480
vtDownload0Width=506
vtDownload1Width=228
vtDownload2Width=154
vtDownload3Width=177
vtDownload4Width=50
vtDownload5Width=126
vtDownload6Width=145
vtFavorites0Width=50
vtFavorites1Width=50
vtFavorites2Width=50
vtFavorites3Width=50
vtFavorites4Width=50
vtAccountList0Width=50
vtAccountList1Width=50
vtAccountList2Width=50
vtAccountList3Width=98

[misc]
SortDownloadColumn=6
SortDownloadDirection=0
SortFavoritesColumn=1
SortFavoritesDirection=0

[BasicListColors]
BackgroundColor=clWindow
BorderColor=clBtnFace
DisabledColor=clBtnShadow
DropMarkColor=clHighlight
DropTargetColor=clHighlight
DropTargetBorderColor=clHotLight
FocusedSelectionColor=clHighlight
FocusedSelectionBorderColor=clHotLight
GridLineColor=clBtnFace
HeaderHotColor=clBtnShadow
HotColor=clWindowText
SelectionRectangleBlendColor=clHighlight
SelectionRectangleBorderColor=clHotLight
TreeLineColor=clBtnShadow
UnfocusedSelectionColor=clBtnFace
UnfocusedSelectionBorderColor=clBtnShadow
NormalTextColor=clWindowText
FocusedSelectionTextColor=clHighlightText
UnfocusedSelectionTextColor=clWindowText
OddColor=clBtnFace
EvenColor=clWindow
SortedColumnColor=$00F8E6D6

[MangaListColors]
NewMangaColor=$00FDC594
CompletedMangaColor=$00B8FFB8

[FavoriteListColors]
BrokenFavoriteColor=$008080FF
CheckingColor=$0080EBFE
NewChapterFoundColor=$00FDC594
CompletedSeriesColor=$00B8FFB8
EmptyChapters=$00CCDDFF

[ChapterListColor]
DownloadedColor=$00B8FFB8

**Comment by rbwz** [comment] 2016-07-28 22:56
Looking at the works.ini, it seems that multiple files was assigned the same filename, thus preventing all the proper files being downloaded.

Perhaps using %NUMBERING% as a possible filename under **options>save to** could circumvent the whole problem as it means no original filename parsing needed.

**Comment by riderkick** [comment] 2016-07-29 03:20
It seems the problem is due to incorrect file name detection. I can't open exhentai right now, don't know why, gateway timeout. So I can't check it.
Using `%NUMBERING%` in custom filename sure will solve the problem.

**Comment by riderkick** [comment] 2016-08-04 16:22
Fixed with https://github.com/riderkick/FMD/commit/21d4c577246ad17897854464efbff62ef42c256e.

**Closed by riderkick** 2016-08-04 16:22 UTC
