### ISSUE TITLE
Failed to create directory

### ISSUE THREAD

**Issue by Kota-Kun** [riderkick/FMD#348] opened 2016-08-13 10:36 UTC
If the names are too long, the manga is not loaded.
![image](https://cloud.githubusercontent.com/assets/4346662/17642721/d124c2d6-6159-11e6-8480-fb0611a381ad.png)
Add the ability to choose either Russian name, or the original.
![image](https://cloud.githubusercontent.com/assets/4346662/17642743/d9ff6d4c-615a-11e6-9684-814d0dab00a7.png)

**Comment by riderkick** [comment] 2016-08-13 12:15
Give me your works.ini

**Comment by Kota-Kun** [comment] 2016-08-13 12:21
[works.ini.txt](https://github.com/riderkick/FMD/files/416549/works.ini.txt)

**Comment by riderkick** [comment] 2016-08-13 14:08
Only the first task is failed on my machine, the other may fixed with this commit https://github.com/riderkick/FMD/commit/7c1346f8be35292324a827aaa6bca3d4b2503ed9.
Seems like the problem is due to combining unicode character in the path, there is a character left in the end after trimmed and turn to another character when combining with path delimiter '\' which become invalid character.

**Comment by Kota-Kun** [comment] 2016-08-13 14:32
you need to remove all special characters \/:*?""<>|~!@#$%^&=` from name.

**Comment by riderkick** [comment] 2016-08-13 15:22
That's already done, it's not ansi symbol but unicode character. Currently we use string which is array of char. char is 1 byte. But 1 unicode character can take more than 1 byte. The problem is when trimming this string, if trimming doesn't correct it can cut at the middle of the character.

**Closed** 2016-08-13 16:36 UTC
