### ISSUE TITLE
0.9.21.3 download failure

### ISSUE THREAD

**Issue by greenaar** [riderkick/FMD#92] opened 2015-08-09 15:09 UTC
Automatic check, 100% failed downloads.  Retried 3 times, 100% failure.  Rolled back to 0.9.20.0 (which i had handy), 100% success resuming those failed downloads on the first try.

**Comment by abhi98** [comment] 2015-08-09 16:18
yup same thing happened to me in FMD

**Comment by riderkick** [comment] 2015-08-09 16:25
Website, title, chapter?

**Comment by greenaar** [comment] 2015-08-09 16:41
I'm using primarily MangaGo and Mangahere -- some mangafox as well.  I've purged the list, so I don't have an example handy, but it was 17 manga, most recent chapters -- I replaced new version with old, and hit retry, and they downloaded without issue.

**Comment by abhi98** [comment] 2015-08-09 16:43
I mostly using Kissmanga and readmanga and sometimes Batoto and mh160.

**Comment by riderkick** [comment] 2015-08-09 16:46
Send me your config.ini where its failed

**Comment by abhi98** [comment] 2015-08-09 16:50
after I restarted and click resume all couple of times in FMD it started working fine again. Sorry

**Comment by abhi98** [comment] 2015-08-09 16:56
So the task fails after you update to the latest version of FMD and then after you restart FMD(after the update) and click resume all, the chapter(s) will be downloaded with no problem

**Comment by riderkick** [comment] 2015-08-09 17:09
There is some changes in config.ini. I suggest you to get fresh config by deleting it, and set everything back manually.

**Comment by greenaar** [comment] 2015-08-09 18:28
Confirmed.  Updated -> new chapters failed.  Hit resume, failed.  Closed app, reopened, hit resume, succeeded.

**Comment by greenaar** [comment] 2015-08-09 18:42
Unfortunately -- new config.ini, any previous favorite fails to download new chapters without closing and reopening the app. rolling back to the last 'stable' version.

**Comment by riderkick** [comment] 2015-08-09 19:26
I really can't reproduce the problem.
Are you sure after update it was version 0.9.21.3 ? right click on fmd.exe > properties > details.

**Comment by greenaar** [comment] 2015-08-09 19:30
Correct. I have upgraded 3 times today, and each time it reports 0.9.21.3 after completing.  It looks like it fails to update any manga which it had stored details for from the older version, until you exit the program and re-open, at which point it downloads with no issues.  No problems detected with fresh downloads either.  A config glitch?

**Comment by riderkick** [comment] 2015-08-09 22:02
All download data stored in works.ini and IIRC there is no change that affect download data since 0.9.20.0.
Are you sure it was the latest version?, the one in about tab wasn't really the version of file, it was static file (readme.rtf). The real file version is on properties>details.
IIRC there is bug in 0.9.20.0 which will show you a warning dialog about empty selected website when launching updater, if you didn't close this dialog and fmd weren't closed before updater finish downloading the update package, updater can't replace fmd.exe.
Another thing is, in older version before fmd launching the updater it will stop all thread and freed all manager, so if fmd aren't closed at this point (due to bug or other case), start/stop will not work, because download manager object already freed.

**Comment by greenaar** [comment] 2015-08-09 22:07
I've re-upgraded and confirmed fmd.exe file version 0.9.21.3, upgraded from 0.9.20.0 -- the warning you mentioned was safely clicked through prior to the upgrade running.

**Comment by riderkick** [comment] 2015-08-09 22:45
Please send me you config.ini and works.ini where its failed. I can't reproduce the problem.

**Comment by greenaar** [comment] 2015-08-09 23:02
Will do, need to wait for another item to update, will attach the files here on the next failure

**Comment by greenaar** [comment] 2015-08-09 23:10
While i wait for another update, here is my config file.  I am compressing to .cbz, and i noticed the failed updates create the folders per chapter (empty), and then are unable to do anything else, on restart of the application with an existing folder the application is able to populate the folder and compress it.

[general]
DownloadFilterSelect=4
MangaListSelect=AnimeA,Authrone,Batoto,EatManga,EyeOnManga,KissManga,KivManga,LoneManga,Madokami,Manga2u,MangaCap,MangaFox,MangaGo,MangaHere,MangaInn,MangaPanda,MangaPark,MangaReader,MangaSee,MangaStreamTo,MangaTown,MangaTraders,NineManga,OneManga,ReadMangaToday,SenManga,Shoujosense,UnixManga
LiveSearch=1
OneInstanceOnly=1
MinimizeToTray=0
NewMangaTime=1
LetFMDDo=0
ExternalProgramPath=
ExternalProgramParams="%PATH%%CHAPTER%"
AddAsStopped=0
HighlightNewManga=1
HighlightDownloadedChapters=1

[languages]
Selected=en

[view]
ShowDownloadsToolbar=1
LoadMangaCover=1

[droptarget]
Show=0
Mode=0
Opacity=255
Width=64
Heigth=64
Top=-1
Left=-1

[connections]
NumberOfTasks=2
NumberOfThreadsPerTask=2
Retry=3
ConnectionTimeout=15
UseProxy=0
ProxyType=HTTP
Host=
Pass=
Port=
User=

[saveto]
SaveTo=d:\comics-fmd\
PathConvert=0
GenerateChapterName=0
GenerateMangaName=1
Compress=2
AutoNumberChapter=1
PDFQuality=100
CustomRename=%NUMBERING% - %CHAPTER%
ConvertDigitVolume=1
ConvertDigitChapter=1
DigitVolumeLength=2
DigitChapterLength=3

[update]
AutoCheckLatestVersion=1
AutoCheckFavStartup=1
AutoCheckFavInterval=1
AutoCheckFavIntervalMinutes=60
AutoCheckFavAutoDownload=1
AutoCheckFavAutoRemoveCompletedManga=1
UpdateListNoMangaInfo=0
UpdateListRemoveDuplicateLocalData=0
AutoCheckUpdate=0
AutoCheckMinutes=60
AutoDownloadFavorites=1
AutoRemoveCompletedManga=1

[dialogs]
ShowQuitDialog=1
ShowDeleteDldTaskDialog=1

[misc]
BatotoShowScanGroup=1
BatotoShowAllLang=0
MangafoxRemoveWatermarks=0
SortDownloadColumn=0
SortDownloadDirection=1
SortFavoritesColumn=1
SortFavoritesDirection=0

[form]
MainSplitter=195
pcMainPageIndex=0
SelectManga=0
MainFormMaximized=0
MainFormLeft=1224
MainFormTop=388
MainFormWidth=640
MainFormHeight=480
vtDownload0Width=300
vtDownload1Width=154
vtDownload2Width=50
vtDownload3Width=50
vtDownload4Width=131
vtDownload5Width=50
vtDownload6Width=213
vtFavorites0Width=50
vtFavorites1Width=563
vtFavorites2Width=50
vtFavorites3Width=254
vtFavorites4Width=259

**Comment by riderkick** [comment] 2015-08-09 23:25
I think there is no problem with your config. I don't recall any major changes in taskthread.execute.

**Comment by greenaar** [comment] 2015-08-09 23:28
Ok, managed to repro it. From 0.9.17, straight upgrade.

Works.ini looks like the following (plus about 150 other lines of the same type:

[general]
NumberOfTasks=165

[task0]
Website=MangaGo
Link=/read-manga/aoi_hikaru_ga_chikyuu_ni_itakoro/
Title="aoi" - Hikaru Ga Chikyuu Ni Itakoro......
SaveTo=D:\comics-fmd\aoi - Hikaru Ga Chikyuu Ni Itakoro.....-\
Status=Failed, try resuming this task!
Progress=
DateTime=42225.6849589699
ChapterLinks=/read-manga/aoi_hikaru_ga_chikyuu_ni_itakoro/mf/328777/Vol1_Ch6/pg-1/!%~/read-manga/aoi_hikaru_ga_chikyuu_ni_itakoro/mf/v01/c007/!%~/read-manga/aoi_hikaru_ga_chikyuu_ni_itakoro/mf/v01/c008/!%~/read-manga/aoi_hikaru_ga_chikyuu_ni_itakoro/mf/329784/Vol1_Ch9/pg-1/!%~/read-manga/aoi_hikaru_ga_chikyuu_ni_itakoro/mf/330274/Vol1_Ch10/pg-1/!%~/read-manga/aoi_hikaru_ga_chikyuu_ni_itakoro/mf/v01/c011/!%~/read-manga/aoi_hikaru_ga_chikyuu_ni_itakoro/mf/v01/c012/!%~/read-manga/aoi_hikaru_ga_chikyuu_ni_itakoro/mf/v01/c013/!%~/read-manga/aoi_hikaru_ga_chikyuu_ni_itakoro/mf/v01/c014/!%~/read-manga/aoi_hikaru_ga_chikyuu_ni_itakoro/mf/333159/Vol1_Ch15/pg-1/!%~
ChapterName=0006 - aoi - Hikaru Ga Chikyuu Ni Itakoro...... Vol.01 Ch.006!%~0007 - aoi - Hikaru Ga Chikyuu Ni Itakoro...... Vol.01 Ch.007  God, Please!%~0008 - aoi - Hikaru Ga Chikyuu Ni Itakoro...... Vol.01 Ch.008!%~0009 - aoi - Hikaru Ga Chikyuu Ni Itakoro...... Vol.01 Ch.009  Where Do People Go When They Die!%~0010 - aoi - Hikaru Ga Chikyuu Ni Itakoro...... Vol.01 Ch.010  The Hikaru That Was Cut Open!%~0011 - aoi - Hikaru Ga Chikyuu Ni Itakoro...... Vol.01 Ch.011!%~0012 - aoi - Hikaru Ga Chikyuu Ni Itakoro...... Vol.01 Ch.012!%~0013 - aoi - Hikaru Ga Chikyuu Ni Itakoro...... Vol.01 Ch.013!%~0014 - aoi - Hikaru Ga Chikyuu Ni Itakoro...... Vol.01 Ch.014  The Stars That Fell From the Sky!%~0015 - aoi - Hikaru Ga Chikyuu Ni Itakoro...... Vol.01 Ch.015  At That Time, I Was on Earth Hoping to Meet You!%~
TaskStatus=STATUS_FAILED
ChapterPtr=0
NumberOfPages=1
CurrentPage=0

[task1]
Website=MangaGo
Link=/read-manga/3d_kanojo/
Title=3d Kanojo
SaveTo=D:\comics-fmd\3d Kanojo\
Status=Failed, try resuming this task!
Progress=
DateTime=42225.6849589815
ChapterLinks=/read-manga/3d_kanojo/mf/v06/c021/!%~
ChapterName=0022 - 3d Kanojo Vol.06 Ch.021  About the Case of My Love Form!%~
TaskStatus=STATUS_FAILED
ChapterPtr=0
NumberOfPages=1
CurrentPage=0

[task2]
Website=Batoto
Link=/comic/_/comics/3-gatsu-no-lion-r528
Title=3-gatsu no Lion
SaveTo=D:\comics-fmd\3-gatsu no Lion\
Status=Failed, try resuming this task!
Progress=
DateTime=42225.6849589815
ChapterLinks=/read/_/328865/3-gatsu-no-lion_v6_ch56_by_be-with-you-scans!%~/read/_/331383/3-gatsu-no-lion_v6_ch57_by_be-with-you-scans!%~/read/_/335468/3-gatsu-no-lion_v6_ch58_by_be-with-you-scans!%~
ChapterName=0023 - Vol.06 Ch.056 Confession [Be With You Scans]!%~0024 - Vol.06 Ch.057 Letter [Be With You Scans]!%~0025 - Vol.06 Ch.058 Start of the Rainy Season [Be With You Scans]!%~
TaskStatus=STATUS_FAILED
ChapterPtr=0
NumberOfPages=1
CurrentPage=0

[task3]
Website=MangaGo
Link=/read-manga/4_god_ranger/
Title=4 God Ranger
SaveTo=D:\comics-fmd\4 God Ranger\
Status=Failed, try resuming this task!
Progress=
DateTime=42225.6849589815
ChapterLinks=/read-manga/4_god_ranger/bt/329876/Ch9/!%~/read-manga/4_god_ranger/bt/manga/4_god_ranger/c010/pg-1/!%~/read-manga/4_god_ranger/bt/335309/Ch11/!%~
ChapterName=0009 - 004 God Ranger Ch.9!%~0010 - 004 God Ranger Ch.10!%~0011 - 004 God Ranger Ch.11!%~
TaskStatus=STATUS_FAILED
ChapterPtr=0
NumberOfPages=1
CurrentPage=0

Initial folders are created (empty).  Resume fails immediately.

**Comment by riderkick** [comment] 2015-08-09 23:49
I still can't reproduce it.
Does it immediately fail, in split seconds? or there is some times before it fail?
Does it even send any http request?
You can try to use local proxy server like handycache, http://handycache.ru. Set proxy in fmd to handycache, you will see every request fmd made logged in handycache.

**Comment by greenaar** [comment] 2015-08-09 23:50
Split second failure.  It looks like it doesn't even try (ie resume goes from in progess to failed in a heartbeat).

**Comment by rhoen91** [comment] 2015-08-10 00:13
I've been experiencing it as well, (minimized in the background)-> auto checking favorites-> then automatic download-> (I check if there's anything new downloaded)all of them failed-> close-> reopen-> resume-> downloads them as normal. It doesn't seem to happen all the time, I think it happens after leaving FMD open on the background for a few hours. or maybe there's something wrong with the auto check -> auto download process

**Comment by kazuoteramoto** [comment] 2015-08-10 00:37
I'm having a similar problem. Batoto, various titles from favorites failed, resume it fails again in a split second. My ´works.ini´ looks like the one by @greenaar 

When trying to resume the failed task no header or anything is sent/receveid (I used ´tcpdump´ to check for anything going to bato.to).

But if I go to the "manga info" page and manually add the last chapter it works fine. Just the fav auto download that fails. 

I don't know if my problem is the same because I'm running fmd on Linux using wine.

**Comment by kazuoteramoto** [comment] 2015-08-10 01:23
Uhh... I have some new info. The favorite is Sidonia from batoto.

Running `strace` and `tcpdump` but without filtering the host I get a GET to reader.shoujosense.com and a 404 from reader.shoujosense.com. But again nothing from bato.to

I don't have shoujosense checked in the websites tab or any fav from shoujosense.

The tcpdump of the HTTP headers http://pastebin.com/dVtVxqzQ
strace of the network calls http://pastebin.com/2gHXWFW2

(Again I'm on linux, so possible not related).

**Closed** 2015-08-10 07:38 UTC

**Comment by riderkick** [comment] 2015-08-10 07:45
I finally able to reproduce the problem, it's just 1 line. 
Next time please explain step by step to reproduce the problem, and better provide config.ini and works.ini if it's related with download list, and favorites.ini if it was related to favorites.
I can't localize the problem if I can't reproduce the problem.
