### ISSUE TITLE
checking new chapters shows every chapter available on website

### ISSUE THREAD

**Issue by adeelshuaib** [riderkick/FMD#297] opened 2016-06-15 22:37 UTC
This is happening with the latest version.

whenever i check for new chapters for favorites, it shows all available chapters of the manga instead of showing just the latest chapter

**Comment by matoro** [comment] 2016-06-15 23:05
Confirming this, although the issue is worded incredibly poorly.  Checks for new chapters of favorites are now downloading ALL chapters for ALL favorites, as well as overwriting old files, regardless of whether there are new chapters or not.

**Comment by riderkick** [comment] 2016-06-15 23:24
duplicate of #293, #295

**Closed by riderkick** 2016-06-15 23:24 UTC
