### ISSUE TITLE
[Request] Auto Backup favorites.ini

### ISSUE THREAD

**Issue by Nandaka** [riderkick/FMD#153] opened 2016-01-02 13:14 UTC
Requesting a feature to automatically backup the favorites.ini file before overwriting the old one, maybe  like a rotating file backup (e.g. favorites.ini.1, favorites.ini.2, etc).

for whatever reason, sometimes I got corrupted/empty favorites.ini after update/refresh the manga list/unclean shutdown.

**Comment by StormJumper** [comment] 2016-01-03 14:31
Your making this harder then it really is. All I did was unzip FMD into it's own separate folder and copied my previous folders data, config, works into the new location and it works fine. I don't overwrite the mangalist as that includes the update list beyond that everything was kept the same and so far I had no problems.

**Comment by Nandaka** [comment] 2016-01-03 15:10
I'm using the updater feature that provided by the application to auto check the latest version and upgrade the application for me.

I'm not sure why my favorite list is gone/reset, that's why I request the backup feature.

**Comment by StormJumper** [comment] 2016-01-04 03:20
I never used that - I just copy the old info to the new just like I did without overwriting the mangalist.ini to preserve.

**Comment by Nandaka** [comment] 2016-01-04 06:36
I prefer the update button, it is one of the feature, why not just use it?

**Comment by StormJumper** [comment] 2016-01-04 14:58
Like I said I rather do a clean install of FMD then update. Update of any kinda have been know to be a hit or miss-that is common knowledge. Why do you just use my other method. Is doing something New/different that hard to do.

**Comment by Nandaka** [comment] 2016-01-04 17:02
then the auto updater feature must be removed, or at least to point to the github release and ask the user to manually copy the folder.

If not, other people might encounter the same issue with me due to broken feature.

**Comment by riderkick** [comment] 2016-01-05 06:38
Auto updater just download, extract and overwrite the existing files. If you look inside the compressed file, there is no config.ini or works folder. So, it should not overwrite your private files. There is no problem with updater as I'm aware of.
Doing multiple saved favorites will not do any good. Where it will make the backup? At launch?, then it will be overwritten in the next cycle. If it's corrupted, then the backup will be corrupted too.

You said "sometimes", it mean there is a problem with it. And we have to sort it out.
I suspect fmd terminated prematurely/forced to close. Try to run fmd with parameter "-LOGACTIVE 4". There will be log folder with text file inside, open this file, there is should be information about fmd being closed normally or not. There is not much information on log file at the moment, just some basic info.

**Comment by Nandaka** [comment] 2016-01-05 07:48
>> Where it will make the backup?
same folder with the original favorites.ini?

>> If it's corrupted, then the backup will be corrupted too.
that's why you have multiple rolling backup (like rolling log file).

>> Try to run fmd with parameter "-LOGACTIVE 4". 
I'll do it. If I encounter the issue, I'll upload it here.

**Comment by riderkick** [comment] 2016-01-05 09:05
Sorry, I mean where in the code, or when it'll doing backup. It'll be useless if there is real issue with storing normal favorites. Our main concern should be here, to localized the real issue when storing favorites to file.
You have to write step by step to reproduce the problem, I can't fix it if I can't reproduce it myself.

**Comment by Nandaka** [comment] 2016-01-05 10:05
> I can't fix it if I can't reproduce it myself.

The thing is I'm not sure why my favorites.ini got reset, so I cannot provide you with the steps.
If you think this request is unnecessary, please close this issue.

Thanks for your great works.

**Comment by riderkick** [comment] 2016-01-05 10:29
Just use it regularly, and if the problem occurs please take a note what you do before it happen, like does favorites checking running, download running or other background thread running(download all/add to favorites/checking update etc).
When fmd closing, it will terminating this threads, and wait for it before saving favorites. https://github.com/riderkick/FMD/blob/master/mangadownloader/forms/frmMain.pas#L1172
But if there is any error in this threads that causing fmd to be terminated prematurely, it will not saving the new favorites.ini. So your files shouldn't be corrupted.
All of this background threads maybe related.
I'll keep this issue open.

**Comment by riderkick** [comment] 2016-01-29 05:15
I'll close it for now. Reopen or create new issue if necessary.

**Closed by riderkick** 2016-01-29 05:15 UTC
Labels: feedback-required
