### ISSUE TITLE
Download and modules increasing; FMD not working

### ISSUE THREAD

**Issue by alexandriatale** [riderkick/FMD#1070] opened 2018-02-27 09:58 UTC
FMD version 148 is suddenly not working. If I open the app, the downloads increased. The total download even exceeds 40 thousands! Also, when I tried to update the software, the modules also increased and I cannot update even though there's new updates. Please help. Thanks in advance

![downloads](https://user-images.githubusercontent.com/33077478/36722098-3c1dd762-1bdf-11e8-8ad2-7b7f56d00115.jpg)

![updates](https://user-images.githubusercontent.com/33077478/36722110-4455e1a4-1bdf-11e8-8cd9-d66665c4a8dd.jpg)

**Comment by Meliodas-Sama** [comment] 2018-02-27 10:43
Try The Latest Release:
https://github.com/riderkick/FMD/releases/latest

**Comment by riderkick** [comment] 2018-02-27 21:05
You update the mangadex module before updating to the latest fmd do you?
Remove mangadex.lua in `lua/modules`.

**Comment by alexandriatale** [comment] 2018-02-28 01:04
I don't know if I update the mangadex module or not, but I didn't have the module when I'm about to delete it

![modules](https://user-images.githubusercontent.com/33077478/36763965-edad672c-1c5c-11e8-81f9-273142ce808b.jpg)

**Comment by riderkick** [comment] 2018-02-28 01:28
That strange behavior is caused by a failed startup event which trigger startup timer to go in loop. #1059  fixed with https://github.com/riderkick/FMD/commit/b84f1c2961450cc85c68e5ccdde156794c04d3d1

The failed startup event caused by duplicate option which is in this case is mangadex module.  there is already mangadex module statically linked in fmd. so it get conflicted with the lua module. mangadex in fmd was removed in later version. fixed with https://github.com/riderkick/FMD/commit/ebfd3af46c68533de38b84ce4602d365871e5c54  https://github.com/riderkick/FMD/commit/5c54533c6eb6071663c929b2d3a00da90f0ff95e

Just update manually should be fine.

**Closed** 2018-02-28 01:29 UTC
