### ISSUE TITLE
Greyscale images rendering as blank pages in PDFs

### ISSUE THREAD

**Issue by matoro** [riderkick/FMD#340] opened 2016-08-04 16:28 UTC
Since the last update new chapters are having all greyscale pages come up blank in PDFs, or rather, PDF readers render them as blank pages due to an error in encoding.  I suspect this is a problem with how color is being encoded: color pages are not affected, as you can see below in the following file.

A sample PDF is here: https://my.mixtape.moe/nipijg.pdf
Downloaded from the chapter http://mangatraders.org/read-online/BokuNoHeroAcademia/chapter-102/index-1/page-1

My suspicions are drawn from a test I attempted via running the file through ```pdfimages```: for each non-color page, it generated the following error:

```
Syntax Warning: Bad Indexed color space (lookup table string too short)
Syntax Error: Bad image parameters
```

Can provide further details if necessary.  Thanks for your hard work!

**Comment by riderkick** [comment] 2016-08-04 17:30
There is no problem with your file. Opened with Foxit Reader.
![sshot-2016-08-05- 01-24-09](https://cloud.githubusercontent.com/assets/4972676/17411575/6dea4150-5aab-11e6-8d4f-fa672db4d9b7.jpg)

In PDF specification it's clearly said the indexed color space (palettes) is limited to <256. Not fixed 255.
Maybe your PDF Viewer always expect it to have 255 color. So it's a bug in your PDF Viewer.

**Comment by riderkick** [comment] 2016-08-04 18:04
Try to open your pdf file with notepad. Look for string `/Indexed /DeviceRGB` there is a number after `/DeviceRGB`, try to decrease it by one, and save your file. Try to open it with you PDF Viewer again. What happen?

**Comment by matoro** [comment] 2016-08-04 19:25
I am using ```evince 3.20.1```

Decreasing that number from 64 to 63 results in the first page becoming corrupted in greyscale https://i.imgur.com/2NrZ6gH.png as well as the color page becoming corrupted https://i.imgur.com/OL7LwcI.png
All other pages stay the same (that is, blank).

Tested in a few other readers:

```mupdf 1.9_a``` has the same problem.  It shows a notification bar reading "errors found on page" for each page.

```xpdf 3.04``` is able to display the file, and does so without any errors.

It would seem that this is a function of how the specific reader handles a color value like that.  However, for maximum cross-compatibility, wouldn't it be best to handle this in a way which causes the fewest problems?  Or is this a function of the images themselves?

**Comment by riderkick** [comment] 2016-08-05 00:15
There is PDF specification that we have to follow, so does all the PDF Viewer. We can't just make "handle this in a way which causes the fewest problem".

The only bug I've found is what fixed with commit above.
The colored one isn't even indexed, it was jpg, which stored as it is using filter DCTDecode, because PDF natively support jpg. Look like the stream is broken, that can be caused by your application to edit this file.
Can you open this file?
[testimage1.pdf](https://github.com/riderkick/FMD/files/402934/testimage1.pdf)
[testimage2.pdf](https://github.com/riderkick/FMD/files/402935/testimage2.pdf)

**Comment by matoro** [comment] 2016-08-05 03:25
Yes, I can open and view both test files just fine with all readers.  So, if I'm understanding you correctly, the problem is not caused by the settings FMD uses for color values?  The test file I uploaded was generated by FMD and not modified at all, so I don't understand how the stream could be broken.

**Comment by riderkick** [comment] 2016-08-05 09:03
It's fixed then.
The problem is what fixed with the commit above. I mistakenly write the `hival` with palettes count, where it should be the highest index or palettes count -1.
What I mean with broken stream is when you edit the file, your "notepad" may changed the encoding or other thing that mess the file when you save it back. Because it's not actually a text file, your "notepad" may be force it to be a text file that broke the stream object. The safe way to edit the file is using hex editor. I edit with notepad++ on Windows without problem though.

**Closed** 2016-08-05 09:16 UTC
