### ISSUE TITLE
Mangafox download problems

### ISSUE THREAD

**Issue by elenras** [riderkick/FMD#698] opened 2017-08-07 19:53 UTC
Hi. I'm at the current version 0.9.122.0 and mostly using mangafox to download manga. The last days had lots of problems with downloading.
Most of the chapter downloads failed and I had to retry a couple of times to get it to finish. Even though I had "retry 10 times if tasks have download problems".
Today I downloaded new chapters and it was worse: The downloads all finished successfully, but most downloads missed at least 70% of the images. I had to add the tasks manually again and then after failing a couple of times, I got all the images.

Do you need any more information? Other than that, I like the tool very much! Thanks for working on it.

**Comment by StormJumper** [comment] 2017-08-11 12:40
Sounds like MangaFox changed their site again to prevent Manga downloaders they will have to look into it but you should give them which manga series you were trying to download so they can reproduce the problem to fix it.

**Comment by riderkick** [comment] 2017-08-11 15:53
Most of the times the problem is with the connections. Probably fixed with auto retry failed task https://github.com/riderkick/FMD/commit/d94cf7cb8f25bef897f0a111c3f4b671888493fd.

**Closed by riderkick** 2017-08-11 15:53 UTC
