### ISSUE TITLE
FlateEncode creates bad PDFs from PNGs

### ISSUE THREAD

**Issue by Matoro** [riderkick/FMD#170] opened 2016-01-24 22:29 UTC
An issue I've had for a while, couldn't figure out why until I started messing around with imagemagick.  An example of a messed-up PDF: https://i.imgur.com/SZbyWxk.jpg.  Note that it only does this for black-and-white images, images with color are unaffected.

**Comment by riderkick** [comment] 2016-01-25 11:01
Can you give me an example of manga+chapter that use png?

**Comment by riderkick** [comment] 2016-01-25 15:51
Please give me the sample. I can't reproduce the problem.
I need this specific image format.

**Comment by Matoro** [comment] 2016-01-26 02:40
Sample PDF:
[Haikyu!! -- [0005] Chapter 4.pdf](https://github.com/riderkick/FMD/files/104352/Haikyu.--.0005.Chapter.4.pdf)

This came from MangaTraders: http://mangatraders.org/read-online/Haikyu

**Comment by riderkick** [comment] 2016-01-26 15:16
It's indexed. I don't know how to embed it to pdf. So I convert it to rgb . The size will be increased.
I'll change when I found the way.

**Closed** 2016-01-26 16:55 UTC
