### ISSUE TITLE
Hang when updating favorites

### ISSUE THREAD

**Issue by blue-lightning** [riderkick/FMD#21] opened 2015-05-06 17:37 UTC
Version: 0.9.9.0
The updater hangs and the program becomes unresponsive after trying to update "Wakabayashi Toshiya's 4-koma Collection" from batoto. My favorites contains only 13 manga, so not because of too many update requests. Restarting doesn't help.

**Comment by riderkick** [comment] 2015-05-06 19:00
Do you mean when checking favorites?
I can't reproduce it. Everything is fine here.
If you don't mind, send me your config.ini and favorites.ini

**Comment by Alter00** [comment] 2015-05-07 03:48
Same here.
When I search for my favorites, it cannot end search, stop at last manga. If you can do something about it I will be glad.
Thanks.

**Comment by riderkick** [comment] 2015-05-07 09:21
As I mention above, I can't reproduce it. Send me your favorites.ini and config.ini.

**Comment by Alter00** [comment] 2015-05-07 15:23
Okay, I uploaded them.
https://userscloud.com/7rp69infxweu
https://userscloud.com/dwk39lpgfyax

**Comment by blue-lightning** [comment] 2015-05-07 16:41
Mine here: http://www.mediafire.com/download/eiejbmfdhfs1s6n/Info.7z
Alter00 is right, after I deleted the manga above the program would hang up on the new last manga.

**Comment by riderkick** [comment] 2015-05-08 09:58
It's due to some of your favorites data is broken.
In your favorites.ini, link of "Himouto! Umaru-chan" is empty. You can check by yourself by opening that file in notepad. It's causing favorite thread to become stuck. On old fmd, favorite thread isn't monitored, so this behavior doesn't appear. But every time we interrupt favorites checking, those threads will set lose and causing memory leaks.
Nevertheless, fmd should recognize this error. Thanks for reporting BTW.

**Comment by riderkick** [comment] 2015-05-08 10:02
Do I should remove broken favorite item automatically upon reading favorites at startup?

**Comment by Alter00** [comment] 2015-05-08 10:24
Can you fix mine without delete any of manga?

**Comment by blue-lightning** [comment] 2015-05-08 11:41
Maybe just a warning dialog with instruction for self-repairing would be better. Auto re-adding that item to get the link would be best, but I guess it could cause problem.

**Comment by Alter00** [comment] 2015-05-08 14:11
I don't have any probematic manga in my list, if I'm not wrong. Also I try it, at Zetman it will not progress anymore, so I removed and added once again but still it didn't.

**Comment by blue-lightning** [comment] 2015-05-08 15:23
How about removing the one dl from S2scanlations (Ao no Exorcist)? Their website seems to be down, but could be from my end. Maybe FMD couldn't locate the website and stuck at that.

**Comment by riderkick** [comment] 2015-05-08 17:12
Filling the link automatically would require to open mangalist before. But that's will take some time(you may notice there is freeze for a while when changing mangalist), and may causing fmd to freeze, except if we process it on another thread. but still that will take time. And fmd will be locked before doing anything to favorites. That'll become more complicated.
I'll just mark it red(probably with exclamation icon) and add a hint when focusing to the list to remove and re-add manually.

**Comment by Alter00** [comment] 2015-05-08 22:02
Thanks, when I delete Ao no exorcist, it fixed.

**Comment by riderkick** [comment] 2015-05-09 01:09
This issue should be fixed with this commit:
https://github.com/riderkick/FMD/commit/51cf4366a5b134dfc2710b10d3b81de881f746e7
https://github.com/riderkick/FMD/commit/ed26446153f0b6aeb9723d8d5f78520032f73f71
https://github.com/riderkick/FMD/commit/e8f195fe3f5107eccce3f979e54128a95877b8c6

**Closed by riderkick** 2015-05-09 01:09 UTC
Labels: bug
