### ISSUE TITLE
FMD Exit way to long

### ISSUE THREAD

**Issue by H4nZ83** [riderkick/FMD#966] opened 2018-02-13 12:19 UTC
FMD exit time was too long, compared on before
it took a whole 2-5 minute to fully close the FMD, including removing the thread from OS..

so it will cause #961

**Comment by riderkick** [comment] 2018-02-13 12:36
Can't reproduce it yet. Probably caused by https://github.com/riderkick/FMD/commit/4af0a0697ce3e4600ed38ea60c74df7c2d86f9dd.

Try to open fmd without doing anything then close. What happens?
Also try to open fmd and do something simple. What happens?
Describe what you do in details and the result.

**Comment by H4nZ83** [comment] 2018-02-13 12:42
okay, i try to open the FMD, do automatic favorites check and waited for the check finish and exit by clicking the close button, select yes from warning messages, then the main windows closes, but there still the tray icon and i still can right click on the tray icon.
before that i following your suggestion on #963 
after the main window closes, i check the task manager and found that it still have some process and keep the cpu util up to around 20% - 25%

and eventually the tray icon missing, but it takes long time to wait the tray icon missing and the FMD.exe images missing from the task manager.

**Comment by H4nZ83** [comment] 2018-02-13 12:44
and i still can click on the RMB menu from tray icon,
as far as i see the menu show drop box working, showing drop box and then when i click it again it closes the drop box

**Comment by H4nZ83** [comment] 2018-02-13 12:45
i think after i click the exit from the tray RMB menu then the FMD really exit

**Comment by H4nZ83** [comment] 2018-02-13 12:47
yup, it because the favorites checking, it wait until all favorites check was done then exit the FMD.
i try to stop the favorites checkin and then exit, FMD exit immediately..

**Comment by riderkick** [comment] 2018-02-13 12:48
25% cpu is indicating its trapped on some loop. Doing a little to none in loop takes the whole cpu resources. 25% means you have 4 cores and 1 cores busy.

**Comment by riderkick** [comment] 2018-02-13 12:50
Enable the log and see what takes long in the log. I put a whole closenow process in log.

**Comment by H4nZ83** [comment] 2018-02-13 13:24
Unhandled exception!
Application       : Free Manga Downloader
Version           : 0.9.138.0
Product Version   : Win32 Debug
Host Machine      : Windows XP
FPC Version       : 3.0.4
LCL Version       : 1.9.0.0
WidgetSet         : Win32/Win64
Target CPU-OS     : i386-Win32
Build Time        : 2018/02/13 16:24:46
Path              : H:\g\Downloader\fmd\fmd.exe
Process ID        : 7612
MainThread ID     : 4952
Thread ID         : 4952
Time              : 13/02/2018 19:15:19.329
Exception Class   : EAccessViolation
Message           : Access violation
  $005EDBC8  TDOWNLOADMANAGER__STOPALLTASKS,  line 1784 of F:/GitRepo/Freepascal/FMD/baseunits/uDownloadsManager.pas
  $00469500  TMAINFORM__TBDOWNLOADSTOPALLCLICK,  line 3833 of ./forms/frmMain.pas
  $005411EE
  $00509A3B
  $7E418734
  $7E418816
  $7E428EA0
  $7E428EEC
  $7C90E473
  $005435B8
  $005D7D02
  $7E418734
  $7E418816
  $7E428EA0
  $7E428EEC
  $7C90E473
  $7E42A43B
Unhandled exception!
Application       : Free Manga Downloader
Version           : 0.9.138.0
Product Version   : Win32 Debug
Host Machine      : Windows XP
FPC Version       : 3.0.4
LCL Version       : 1.9.0.0
WidgetSet         : Win32/Win64
Target CPU-OS     : i386-Win32
Build Time        : 2018/02/13 16:24:46
Path              : H:\g\Downloader\fmd\fmd.exe
Process ID        : 6312
MainThread ID     : 7432
Thread ID         : 7432
Time              : 13/02/2018 19:43:03.110
Exception Class   : EAccessViolation
Message           : Access violation
  $005EDBC8  TDOWNLOADMANAGER__STOPALLTASKS,  line 1784 of F:/GitRepo/Freepascal/FMD/baseunits/uDownloadsManager.pas
  $00469500  TMAINFORM__TBDOWNLOADSTOPALLCLICK,  line 3833 of ./forms/frmMain.pas
  $005411EE
  $00509A3B
  $7E418734
  $7E418816
  $7E428EA0
  $7E428EEC
  $7C90E473
  $005435B8
  $005D7D02
  $7E418734
  $7E418816
  $7E428EA0
  $7E428EEC
  $7C90E473
  $7E42A43B
=== Log Session Started at 2/13/2018 20:19:04 by Free Manga Downloader ===
20:19:04:235 INFO: "Free Manga Downloader" started with [PID:5800] [HANDLE:4294967295]
20:19:04:251 STRINGS: Application info
               Application       : Free Manga Downloader
               Version           : 0.9.138.0
               Product Version   : Win32 Debug
               Host Machine      : Windows XP
               FPC Version       : 3.0.4
               LCL Version       : 1.9.0.0
               WidgetSet         : Win32/Win64
               Target CPU-OS     : i386-Win32
               Build Time        : 2018/02/13 16:24:46
               Path              : H:\g\Downloader\fmd\fmd.exe
               Process ID        : 5800
               MainThread ID     : 5608
20:19:20:376 INFO: TMainForm.FormClose
20:19:21:407 INFO: TMainForm.CloseNow, disabling all timer
20:19:21:407 INFO: TMainForm.CloseNow, backup downloads
20:19:22:017 INFO: TMainForm.CloseNow, backup favorites
20:19:23:220 INFO: TMainForm.CloseNow, backup all data to file
20:19:23:220 INFO: TMainForm.CloseNow, closSaveFormInformationing other forms
20:19:23:235 INFO: TMainForm.CloseNow, stop ipc server
20:19:23:235 INFO: TMainForm.FormDestroy, freeing all objects
20:19:25:345 INFO: "Free Manga Downloader" exit normally [PID:5800] [HANDLE:4294967295]
20:21:02:579 INFO: TMainForm.FormClose
20:21:02:595 INFO: TMainForm.FormClose aborted!
20:21:14:720 INFO: TMainForm.FormClose
20:21:14:751 INFO: TMainForm.FormClose aborted!
20:22:57:923 INFO: TMainForm.FormClose
20:22:57:954 INFO: TMainForm.FormClose aborted!

**Comment by H4nZ83** [comment] 2018-02-13 13:25
and now still not closing i think the formclose and form close aborted was triggered when i click the exit from tray righ menu

**Comment by H4nZ83** [comment] 2018-02-13 13:28
and now still not closing i think the formclose and form close aborted was triggered when i click the exit from tray right menu.
the taskbar button show itself, after i click the restore from tray menu

**Comment by H4nZ83** [comment] 2018-02-13 13:30
20:21:02:579 INFO: TMainForm.FormClose
20:21:02:595 INFO: TMainForm.FormClose aborted!
20:21:14:720 INFO: TMainForm.FormClose
20:21:14:751 INFO: TMainForm.FormClose aborted!
20:22:57:923 INFO: TMainForm.FormClose
20:22:57:954 INFO: TMainForm.FormClose aborted!
20:29:20:376 INFO: TMainForm.FormClose
20:29:20:407 INFO: TMainForm.FormClose aborted!
20:29:23:220 INFO: TMainForm.FormClose
20:29:23:235 INFO: TMainForm.FormClose aborted!
20:29:27:298 EXCEPTION: EAccessViolation - Access violation
                 $005EDBC8  TDOWNLOADMANAGER__STOPALLTASKS,  line 1784 of F:/GitRepo/Freepascal/FMD/baseunits/uDownloadsManager.pas
                 $00469500  TMAINFORM__TBDOWNLOADSTOPALLCLICK,  line 3833 of ./forms/frmMain.pas
                 $005411EE
                 $00509A3B
                 $7E418734
                 $7E418816
                 $7E428EA0
                 $7E428EEC
                 $7C90E473
                 $005435B8
                 $005D7D02
                 $7E418734
                 $7E418816
                 $7E428EA0
                 $7E428EEC
                 $7C90E473
                 $7E42A43B

**Comment by H4nZ83** [comment] 2018-02-13 13:30
the thread close after i choose stop all task from the tray menu

**Comment by riderkick** [comment] 2018-02-13 13:39
Still can't reproduce you issue. You don't have a single log about closing any thread. That means you don't have any running threads.
Here is my log.
```
21:36:10:898 INFO: TMainForm.FormClose
21:36:10:900 INFO: TMainForm.CloseNow, terminating check favorites threads
21:36:10:980 INFO: TMainForm.CloseNow, check favorites threads terminated
21:36:10:982 INFO: TMainForm.CloseNow, terminating downloads threads
21:36:11:047 INFO: TMainForm.CloseNow, downlads threads terminated
21:36:11:049 INFO: TMainForm.CloseNow, disabling all timer
21:36:11:106 INFO: TMainForm.CloseNow, backup downloads
21:36:11:270 INFO: TMainForm.CloseNow, backup favorites
21:36:11:463 INFO: TMainForm.CloseNow, backup all data to file
21:36:11:497 INFO: TMainForm.CloseNow, close other forms
21:36:11:506 INFO: TMainForm.FormDestroy, freeing all objects
21:36:12:000 INFO: "Free Manga Downloader" exit normally [PID:11868] [HANDLE:4294967295]
```

**Comment by H4nZ83** [comment] 2018-02-13 13:47
yeah, but in my machine the FMD still running even after the 
"Free Manga Downloader" exit normally [PID:xxxx] [HANDLE:xxxxx]

okay check this, try to enable minimize to tray form option, then after that do as you sugested from #963
then try to exit without changing any of the option

the problem caused by the minimize to tray option that bugged, when i enable it and then disable it again the problem was gone

**Comment by H4nZ83** [comment] 2018-02-13 13:48
ops, the problem existed again when you run the FMD for second time after disabling the option

**Comment by riderkick** [comment] 2018-02-13 13:50
Not sure if it's related to #963, but you can try.

[fmd_win32.7z.txt](https://github.com/riderkick/FMD/files/1720066/fmd_win32.7z.txt)

**Comment by H4nZ83** [comment] 2018-02-13 13:51
oh the problem was happened when you run then exit the FMD then running it again for second times then the problem exist, if you force end task from task manager then the problem solved, but then when you run the FMD again then exit the problem came up

**Comment by H4nZ83** [comment] 2018-02-13 13:52
rogram exception!
Application       : Free Manga Downloader
Version           : 0.9.138.0
Product Version   : Win32 Debug
Host Machine      : Windows XP
FPC Version       : 3.0.4
LCL Version       : 1.9.0.0
WidgetSet         : Win32/Win64
Target CPU-OS     : i386-Win32
Build Time        : 2018/02/13 16:24:46
Path              : H:\g\Downloader\fmd\fmd.exe
Process ID        : 7108
MainThread ID     : 6780
Thread ID         : 2800
Time              : 13/02/2018 20:51:38.990
Sender Class      : TTaskThread
Exception Class   : EInOutError
Message           : Access denied
  In TTaskThread.Execute
  Flag        : CS_DOWNLOAD
  Website     : MangaFox
  Title       : DICE: The Cube that Changes Everything
  Chapterlink : /manga/dice_the_cube_that_changes_everything/v02/c221/
  Chaptername : DICE The Cube that Changes Everything 221 Stage 221 Chicken Game (3)

  $004734C7
  $00472784
  $00472DE7
  $005EB712  CHECKFORFINISH,  line 966 of F:/GitRepo/Freepascal/FMD/baseunits/uDownloadsManager.pas
  $005EAD36  TTASKTHREAD__EXECUTE,  line 1155 of F:/GitRepo/Freepascal/FMD/baseunits/uDownloadsManager.pas
  $00444AD5
  $00412D2E
  $7C80B729

**Comment by H4nZ83** [comment] 2018-02-13 13:52
rogram exception!
Application       : Free Manga Downloader
Version           : 0.9.138.0
Product Version   : Win32 Debug
Host Machine      : Windows XP
FPC Version       : 3.0.4
LCL Version       : 1.9.0.0
WidgetSet         : Win32/Win64
Target CPU-OS     : i386-Win32
Build Time        : 2018/02/13 16:24:46
Path              : H:\g\Downloader\fmd\fmd.exe
Process ID        : 7108
MainThread ID     : 6780
Thread ID         : 2800
Time              : 13/02/2018 20:51:38.990
Sender Class      : TTaskThread
Exception Class   : EInOutError
Message           : Access denied
  In TTaskThread.Execute
  Flag        : CS_DOWNLOAD
  Website     : MangaFox
  Title       : DICE: The Cube that Changes Everything
  Chapterlink : /manga/dice_the_cube_that_changes_everything/v02/c221/
  Chaptername : DICE The Cube that Changes Everything 221 Stage 221 Chicken Game (3)

  $004734C7
  $00472784
  $00472DE7
  $005EB712  CHECKFORFINISH,  line 966 of F:/GitRepo/Freepascal/FMD/baseunits/uDownloadsManager.pas
  $005EAD36  TTASKTHREAD__EXECUTE,  line 1155 of F:/GitRepo/Freepascal/FMD/baseunits/uDownloadsManager.pas
  $00444AD5
  $00412D2E
  $7C80B729

**Comment by H4nZ83** [comment] 2018-02-13 13:52
Program exception!
Application       : Free Manga Downloader
Version           : 0.9.138.0
Product Version   : Win32 Debug
Host Machine      : Windows XP
FPC Version       : 3.0.4
LCL Version       : 1.9.0.0
WidgetSet         : Win32/Win64
Target CPU-OS     : i386-Win32
Build Time        : 2018/02/13 16:24:46
Path              : H:\g\Downloader\fmd\fmd.exe
Process ID        : 7108
MainThread ID     : 6780
Thread ID         : 6972
Time              : 13/02/2018 20:52:16.849
Sender Class      : TTaskThread
Exception Class   : EInOutError
Message           : Access denied
  In TTaskThread.Execute
  Flag        : CS_DOWNLOAD
  Website     : FunManga
  Title       : Apotheosis - Elevation to the status of a god
  Chapterlink : /apotheosis-elevation-to-the-status-of-a-god/14
  Chaptername : Apotheosis - Elevation to the status of a god 014

  $004734C7
  $00472784
  $00472DE7
  $005EB712  CHECKFORFINISH,  line 966 of F:/GitRepo/Freepascal/FMD/baseunits/uDownloadsManager.pas
  $005EAD36  TTASKTHREAD__EXECUTE,  line 1155 of F:/GitRepo/Freepascal/FMD/baseunits/uDownloadsManager.pas
  $00444AD5
  $00412D2E
  $7C80B729

**Comment by H4nZ83** [comment] 2018-02-13 13:54
there was 2 more error after i force close the FMD from task manager
and after running it for second time after normal exit the problem was gone

**Comment by H4nZ83** [comment] 2018-02-13 14:00
okay i'll try to check if the update you gave me was solved the problem

still got the problem but it generate a .trc files ?

**Comment by H4nZ83** [comment] 2018-02-13 14:01
and a blank command prompt box appeared

**Comment by H4nZ83** [comment] 2018-02-13 14:04
here the trc file 
[fmd.trc.txt](https://github.com/riderkick/FMD/files/1720143/fmd.trc.txt)
and the log files
[fmd.log.txt](https://github.com/riderkick/FMD/files/1720148/fmd.log.txt)

**Comment by riderkick** [comment] 2018-02-13 14:35
There is no stalled threads.
Cleanup you fmd.log
Try changing your selected websites then save.

[fmd_win32.7z.txt](https://github.com/riderkick/FMD/files/1720193/fmd_win32.7z.txt)

**Comment by H4nZ83** [comment] 2018-02-14 01:59
i think after i'm updating with the most recent version and then try to do some task. 
and it worked, it exit directly

**Comment by riderkick** [comment] 2018-02-14 02:02
It's fixed?
Then close the issue.

**Closed** 2018-02-14 02:02 UTC
