### ISSUE TITLE
kissmanga won't download with latest release 0.9.127.0

### ISSUE THREAD

**Issue by contrasena** [riderkick/FMD#788] opened 2017-11-18 22:03 UTC
First: Thank you so much for this incredible program!!. 
But the latest release (0.9.127.0 from today) doesn't download from kissmanga (at least on my setup). Reverting to 0.9.125.0 fixed the issue.

I'm using Linux Mint 18 with WINE installed from ofiicial repos on synaptic.

Thank you again.

**Comment by yuushin51** [comment] 2017-11-19 06:19
Me too, reverting back to 0.9.126.0 and it can get chapter pages again.
0.9.127.0 it just keep retrying with 1 page and finally fail.

**Comment by spamtaztik** [comment] 2017-11-19 15:15
I can confirm the same issue with kissmanga. Reverting back to 126.

**Comment by StormJumper** [comment] 2017-11-20 01:02
So what is the issue exactly with not downloading kissmanga? WINE was never a replacement for a actual O/S so others are you using the same setup as well?

**Comment by yuushin51** [comment] 2017-11-20 01:24
Nope, I'm using win7 64bit.

**Comment by spamtaztik** [comment] 2017-11-20 03:53
Oh, sorry I forgot to mention my OS. I'm using win7 x64 as well. The downloads would just stay at 1/1 instead of the actual number of pages for those chapters. After that they would just stop and say "failed".

**Comment by molitar** [comment] 2017-11-20 06:59
Same here

**Comment by molitar** [comment] 2017-11-20 07:01
Where can I download the old version?

**Comment by yuushin51** [comment] 2017-11-20 07:45
here https://github.com/riderkick/FMD/releases

**Comment by Tmp341** [comment] 2017-11-20 12:46
Downloaded new version for testing, and it seems like kissmanga stopped working. 

> === Log Session Started at 20.11.2017 15:39:55 by Free Manga Downloader ===
15:39:55:877 INFO: "Free Manga Downloader" started with [PID:11652] [HANDLE:18446744073709551615]
15:39:55:892 STRINGS: Application info
               Application       : Free Manga Downloader
               Version           : 0.9.127.0 
               Product Version   : Win64 Debug 
               Host Machine      : Windows 10 64-bit
               FPC Version       : 3.1.1
               LCL Version       : 1.9.0.0
               WidgetSet         : Win32/Win64
               Target CPU-OS     : x86_64-Win64
               Build Time        : 2017/11/19 02:52:45
               Path              : D:\Program Files\Portable\Fmd\fmd.exe
               Process ID        : 11652
               MainThread ID     : 10204
15:42:09:610 WARNING: TTaskThread, checkforfinish failed=1/1 "Dadadadan." > "/Manga/Dadadadan/Vol-004-Ch-015-001--C-c-cops-and-Robbers-Story?id=375955"
W
15:42:09:614 WARNING: TTaskThread, download failed. "Dadadadan." "Dadadadan. Vol.004 Ch.015.001 C-c-cops and Robbers Story" "/Manga/Dadadadan/Vol-004-Ch-015-001--C-c-cops-and-Robbers-Story?id=375955"
15:42:14:122 WARNING: TTaskThread, checkforfinish failed=1/1 "Dadadadan." > "/Manga/Dadadadan/Vol-004-Ch-015-002--D-D-D-Duel-Story?id=377920"
W
15:42:14:126 WARNING: TTaskThread, download failed. "Dadadadan." "Dadadadan. Vol.004 Ch.015.002 D-D-D-Duel Story" "/Manga/Dadadadan/Vol-004-Ch-015-002--D-D-D-Duel-Story?id=377920"
15:42:18:136 WARNING: TTaskThread, checkforfinish failed=1/1 "Dadadadan." > "/Manga/Dadadadan/Vol-004-Ch-015-003--E-E-E-Extra-Story?id=377921"
W
15:42:18:140 WARNING: TTaskThread, download failed. "Dadadadan." "Dadadadan. Vol.004 Ch.015.003 E-E-E-Extra Story" "/Manga/Dadadadan/Vol-004-Ch-015-003--E-E-E-Extra-Story?id=377921"
15:42:22:150 WARNING: TTaskThread, checkforfinish failed=1/1 "Dadadadan." > "/Manga/Dadadadan/Vol-005-Ch-016?id=383078"
W
15:42:22:154 WARNING: TTaskThread, download failed. "Dadadadan." "Dadadadan. Vol.005 Ch.016" "/Manga/Dadadadan/Vol-005-Ch-016?id=383078"
15:42:26:184 WARNING: TTaskThread, checkforfinish failed=1/1 "Dadadadan." > "/Manga/Dadadadan/Vol-005-Ch-017?id=385127"
W
15:42:26:188 WARNING: TTaskThread, download failed. "Dadadadan." "Dadadadan. Vol.005 Ch.017" "/Manga/Dadadadan/Vol-005-Ch-017?id=385127"
15:42:31:701 WARNING: TTaskThread, checkforfinish failed=1/1 "Dadadadan." > "/Manga/Dadadadan/Vol-005-Ch-018?id=386135"
W
15:42:31:705 WARNING: TTaskThread, download failed. "Dadadadan." "Dadadadan. Vol.005 Ch.018" "/Manga/Dadadadan/Vol-005-Ch-018?id=386135"
15:42:35:214 WARNING: TTaskThread, checkforfinish failed=1/1 "Dadadadan." > "/Manga/Dadadadan/Vol-005-Ch-019?id=387282"
W
15:42:35:218 WARNING: TTaskThread, download failed. "Dadadadan." "Dadadadan. Vol.005 Ch.019" "/Manga/Dadadadan/Vol-005-Ch-019?id=387282"
15:42:38:729 WARNING: TTaskThread, checkforfinish failed=1/1 "Dadadadan." > "/Manga/Dadadadan/Vol-005-Ch-019-005--Volume-005-extras?id=387283"
W
15:42:38:733 WARNING: TTaskThread, download failed. "Dadadadan." "Dadadadan. Vol.005 Ch.019.005 Volume 005 extras" "/Manga/Dadadadan/Vol-005-Ch-019-005--Volume-005-extras?id=387283"
15:42:44:245 WARNING: TTaskThread, checkforfinish failed=1/1 "Dadadadan." > "/Manga/Dadadadan/Vol-004-Ch-015-001--C-c-cops-and-Robbers-Story?id=375955"
W
15:42:44:249 WARNING: TTaskThread, download failed. "Dadadadan." "Dadadadan. Vol.004 Ch.015.001 C-c-cops and Robbers Story" "/Manga/Dadadadan/Vol-004-Ch-015-001--C-c-cops-and-Robbers-Story?id=375955"
15:42:47:759 WARNING: TTaskThread, checkforfinish failed=1/1 "Dadadadan." > "/Manga/Dadadadan/Vol-004-Ch-015-002--D-D-D-Duel-Story?id=377920"
W
15:42:47:764 WARNING: TTaskThread, download failed. "Dadadadan." "Dadadadan. Vol.004 Ch.015.002 D-D-D-Duel Story" "/Manga/Dadadadan/Vol-004-Ch-015-002--D-D-D-Duel-Story?id=377920"
15:42:51:275 WARNING: TTaskThread, checkforfinish failed=1/1 "Dadadadan." > "/Manga/Dadadadan/Vol-004-Ch-015-003--E-E-E-Extra-Story?id=377921"
W
15:42:51:279 WARNING: TTaskThread, download failed. "Dadadadan." "Dadadadan. Vol.004 Ch.015.003 E-E-E-Extra Story" "/Manga/Dadadadan/Vol-004-Ch-015-003--E-E-E-Extra-Story?id=377921"
15:42:55:287 WARNING: TTaskThread, checkforfinish failed=1/1 "Dadadadan." > "/Manga/Dadadadan/Vol-005-Ch-016?id=383078"
W
15:42:55:291 WARNING: TTaskThread, download failed. "Dadadadan." "Dadadadan. Vol.005 Ch.016" "/Manga/Dadadadan/Vol-005-Ch-016?id=383078"
15:42:59:302 WARNING: TTaskThread, checkforfinish failed=1/1 "Dadadadan." > "/Manga/Dadadadan/Vol-005-Ch-017?id=385127"
W
15:42:59:306 WARNING: TTaskThread, download failed. "Dadadadan." "Dadadadan. Vol.005 Ch.017" "/Manga/Dadadadan/Vol-005-Ch-017?id=385127"
15:43:03:817 WARNING: TTaskThread, checkforfinish failed=1/1 "Dadadadan." > "/Manga/Dadadadan/Vol-005-Ch-018?id=386135"
W
15:43:03:821 WARNING: TTaskThread, download failed. "Dadadadan." "Dadadadan. Vol.005 Ch.018" "/Manga/Dadadadan/Vol-005-Ch-018?id=386135"
15:43:08:832 WARNING: TTaskThread, checkforfinish failed=1/1 "Dadadadan." > "/Manga/Dadadadan/Vol-005-Ch-019?id=387282"
W
15:43:08:836 WARNING: TTaskThread, download failed. "Dadadadan." "Dadadadan. Vol.005 Ch.019" "/Manga/Dadadadan/Vol-005-Ch-019?id=387282"
15:43:13:847 WARNING: TTaskThread, checkforfinish failed=1/1 "Dadadadan." > "/Manga/Dadadadan/Vol-005-Ch-019-005--Volume-005-extras?id=387283"
W
15:43:13:851 WARNING: TTaskThread, download failed. "Dadadadan." "Dadadadan. Vol.005 Ch.019.005 Volume 005 extras" "/Manga/Dadadadan/Vol-005-Ch-019-005--Volume-005-extras?id=387283"

**Comment by Tmp341** [comment] 2017-11-20 13:28
Confirmed. Going back to v0.9.126.0 solves Kissmanga problem.

**Comment by shinsuke89** [comment] 2017-11-21 08:02
how to going back to old version with listed favourite manga from latest version?

**Comment by Renvix** [comment] 2017-11-21 09:04
me too

**Comment by Tmp341** [comment] 2017-11-21 09:27
Back up "favorites.db" file in "Works" folder.

**Comment by Leguron** [comment] 2017-11-21 18:31
I also experience that problem.

Using this trick

"For key type 'chko'.
For iv type 'CryptoJS.enc.Hex.stringify(iv)'
Copy the result without quote."

is also not working anymore. I guess I'll download the old version and disable auto update. 

What am I missing from the new version?

Also since Kissmanga is always causing trouble. From the supported website in FMD which host offers a similiar list of manga in the same kind of quality?

**Comment by Tmp341** [comment] 2017-11-24 08:37
I use batoto, mangago, mangasee, mangastream and mangazuki. But i also use scanlators websites too. 

Main idea is, i go have a look on Mangaupdates, which manga has which chapter released lastly. Then i look at these websites, which one contains full releases. Then i download from there.

**Comment by molitar** [comment] 2017-12-02 06:05
Has anyone found a fix for this?  I am stuck on .126 because .127 does not work with kissmanga.. So I have many sites broken now and does not look like we will see a .128 anytime soon.

**Comment by Leguron** [comment] 2017-12-03 18:00
Still no fix. I also can't download with .126 from kissmanga anymore. I changed the key and Initialization Vector but still not working. 

So if it's also happening to you there is no point then to stay on .126

**Comment by molitar** [comment] 2017-12-03 19:49
No it works on .126 for downloads still so no point to go to .127 waiting for .128 whenever that will be :(

**Comment by Tmp341** [comment] 2017-12-04 12:58
Now kissmanga gone here too. I can open it from browser. I can check manga info but when i start to download, this happens:
![2](https://user-images.githubusercontent.com/1683388/33553958-e263517c-d90b-11e7-8563-4a195a19da8a.gif)

**Comment by spamtaztik** [comment] 2017-12-07 15:28
@Tmp341 : For the kissmanga "1/1 Failed blah blah" thing, I have a workaround for that. 

Close FMD, then use your browser to open kissmanga. Wait a bit, run FMD again (don't close the browser just yet), then try resuming those tasks. Kissmanga downloads seem to work for me after that. Try it out and let me know if it works for you.

**Comment by molitar** [comment] 2017-12-08 04:05
@spamtaztik  did not work for me all I get is the error in logs.

`23:04:19:299 WARNING: TTaskThread, checkforfinish failed=1/1 "1 Love 9" > "/Manga/1-Love-9/1-Love-9-1?id=73102"
W
23:04:19:299 WARNING: TTaskThread, download failed. "1 Love 9" "001 Love 9 001 Greetings" "/Manga/1-Love-9/1-Love-9-1?id=73102"
23:04:21:300 WARNING: TTaskThread, checkforfinish failed=1/1 "1 Love 9" > "/Manga/1-Love-9/1-Love-9-2?id=73105"
W
23:04:21:300 WARNING: TTaskThread, download failed. "1 Love 9" "001 Love 9 002 The Battle for Number 003" "/Manga/1-Love-9/1-Love-9-2?id=73105"
23:04:23:301 WARNING: TTaskThread, checkforfinish failed=1/1 "1 Love 9" > "/Manga/1-Love-9/1-Love-9-1?id=73102"
W
23:04:23:301 WARNING: TTaskThread, download failed. "1 Love 9" "001 Love 9 001 Greetings" "/Manga/1-Love-9/1-Love-9-1?id=73102"`

**Comment by spamtaztik** [comment] 2017-12-08 04:38
Huh that's odd... It's working fine for me. Have you tried at a later time?
Like I said, some of my tasks need several tries (and sometimes at
different hours of the day) before they all succeeded.

**Comment by molitar** [comment] 2017-12-08 04:43
Oh yeah .126 worked without any of that extra stuff.. I also tried .127 with cookies no go.. .127 is 100% utterly broken with Kissmanga :(

**Comment by garybempo** [comment] 2017-12-08 08:53
@molitar 
how about now(Dec 8th)?  0.9.126 not working for me on Kissmanga

I don't know other manga side so randomly chose MangaFox for the meantime.

**Comment by Leguron** [comment] 2017-12-21 20:06
Kissmanga broken again?

**Closed** 2017-12-23 14:35 UTC
